---

- include: install.yml
  tags:
    - grafana.install

- include: configure.yml
  tags:
    - grafana.configure

- include: provisioning.yml
  tags:
    - grafana.provisioning

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: true
